---
# task/prerequisites file for deploy_keepalived
- name: "Install compilation dependencies"
  ansible.builtin.include_role:
    name: ednz_cloud.manage_apt_packages
  vars:
    manage_apt_packages_list: "{{ deploy_keepalived_required_packages }}"
  when: deploy_keepalived_deploy_method == 'host'

- name: "Create directory {{ deploy_keepalived_config_dir }}"
  ansible.builtin.file:
    path: "{{ deploy_keepalived_config_dir }}"
    state: directory
    owner: "{{ deploy_keepalived_user }}"
    group: "{{ deploy_keepalived_group }}"
    mode: "0755"

- name: "Create directory {{ deploy_keepalived_scripts_dir }}"
  ansible.builtin.file:
    path: "{{ deploy_keepalived_scripts_dir }}"
    state: directory
    owner: "{{ deploy_keepalived_user }}"
    group: "{{ deploy_keepalived_group }}"
    mode: "0755"
